# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 304c9e618c3878bb7ef695f0783aad784fecde61e25c2851057a9a1105c79587bc42876a8d2157f64107ba079a2c77947b2c4ec3b8fa8dd92fe1d2f403980212

test:
  secret_key_base: 0cb2458bd91a87c8084a88473f92956fe1a2a37c41127307dbb05b301624eef95f197f65456d36fee6bb34f83496d53bfefcca282632525a19c402c934077eef

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
